### ISSUE TITLE
Watching non-existent files always returns an error

### ISSUE THREAD

**Issue by ricochet1k** [limetext/lime-backend#89]
in lib/watch/watcher.go, if you watch a file that doesn't currently exist, it always returns the confusing error `The callback argument does satisfy any File*Callback interfaces`

This happens because line 68 tries to watch the parent directory with a nil callback.

**Comment by zoli** [comment]
The exact cause of this is when we want to watch a non-existent file, The watcher tries to watch the file directory but if the directory doesn't exist to this error will happen.
> This happens because line 68 tries to watch the parent directory with a nil callback.

[line 75](https://github.com/limetext/lime-backend/blob/7392b2626938bfb62808c8d7ce4b5e7b463fd21c/lib/watch/watcher.go#L75) checks if it is a directory it won't return an error.

I think this error was caused because `User` directory was missing in [lime-packages](https://github.com/limetext/lime-packages) I added it here https://github.com/limetext/lime-packages/commit/648ef5277a680c7758dc6c47d8565d3a98eaee7c.

Not exactly related but after the change mentioned before on lime-packages and https://github.com/limetext/lime-backend/commit/95dc3b16464099ded5e1a47f8113e66e1002c290 most of unnecessary warnings are removed.

**Comment by ricochet1k** [comment]
Ah, right. I don't see it anymore. Thanks.
